using System.Globalization;
using System.IO;
using System.Text;
using JackTheRipper360.Core.Common;

namespace JackTheRipper360.Core.Models
{
    /// <summary>
    /// FBX export using the ASCII FBX 7.x format.
    /// This is a pure C# implementation that generates valid FBX ASCII files
    /// without requiring Autodesk's SDK.
    /// </summary>
    public static class FbxExporterBridge
    {
        /// <summary>
        /// Export mesh data to FBX ASCII format.
        /// </summary>
        public static ExportResult ExportToFBX(MeshData mesh, string outputPath)
        {
            if (mesh == null || mesh.Vertices.Count == 0)
                return ExportResult.Failed("No mesh data to export.");

            string fbxContent = GenerateFBXAscii(mesh);
            string fbxPath = Path.ChangeExtension(outputPath, ".fbx");
            File.WriteAllText(fbxPath, fbxContent);
            return ExportResult.Succeeded(fbxPath, fbxContent.Length);
        }

        private static string GenerateFBXAscii(MeshData mesh)
        {
            var sb = new StringBuilder();
            string meshName = mesh.Name ?? "Xbox360Mesh";

            // FBX Header
            sb.AppendLine("; FBX 7.4.0 project file");
            sb.AppendLine("; Generated by JackTheRipper360 - Xbox 360 Asset Extractor");
            sb.AppendLine("FBXHeaderExtension:  {");
            sb.AppendLine("    FBXHeaderVersion: 1003");
            sb.AppendLine("    FBXVersion: 7400");
            sb.AppendLine("}");
            sb.AppendLine();

            // Global settings
            sb.AppendLine("GlobalSettings:  {");
            sb.AppendLine("    Version: 1000");
            sb.AppendLine("    Properties70:  {");
            sb.AppendLine("        P: \"UpAxis\", \"int\", \"Integer\", \"\",1");
            sb.AppendLine("        P: \"UpAxisSign\", \"int\", \"Integer\", \"\",1");
            sb.AppendLine("        P: \"FrontAxis\", \"int\", \"Integer\", \"\",2");
            sb.AppendLine("        P: \"FrontAxisSign\", \"int\", \"Integer\", \"\",1");
            sb.AppendLine("        P: \"CoordAxis\", \"int\", \"Integer\", \"\",0");
            sb.AppendLine("        P: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1");
            sb.AppendLine("        P: \"UnitScaleFactor\", \"double\", \"Number\", \"\",1");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // Objects
            sb.AppendLine("Objects:  {");

            // Geometry (Mesh)
            long geometryId = 100000;
            long modelId = 200000;
            long materialId = 300000;

            sb.AppendLine($"    Geometry: {geometryId}, \"Geometry::{meshName}\", \"Mesh\" {{");

            // Vertices
            sb.Append("        Vertices: *" + (mesh.Vertices.Count * 3) + " {\n            a: ");
            for (int i = 0; i < mesh.Vertices.Count; i++)
            {
                var v = mesh.Vertices[i];
                if (i > 0) sb.Append(",");
                sb.Append(string.Format(CultureInfo.InvariantCulture, "{0:F6},{1:F6},{2:F6}", v.X, v.Y, v.Z));
            }
            sb.AppendLine("\n        }");

            // Polygon vertex indices (triangles)
            sb.Append("        PolygonVertexIndex: *" + mesh.Indices.Count + " {\n            a: ");
            for (int i = 0; i < mesh.Indices.Count; i += 3)
            {
                if (i > 0) sb.Append(",");
                int i0 = mesh.Indices[i];
                int i1 = mesh.Indices[i + 1];
                int i2 = mesh.Indices[i + 2];
                // FBX uses negative index - 1 for last vertex of polygon
                sb.Append($"{i0},{i1},{~i2}");
            }
            sb.AppendLine("\n        }");

            // Normals
            if (mesh.Normals.Count > 0)
            {
                sb.AppendLine("        LayerElementNormal: 0 {");
                sb.AppendLine("            Version: 101");
                sb.AppendLine("            Name: \"\"");
                sb.AppendLine("            MappingInformationType: \"ByVertice\"");
                sb.AppendLine("            ReferenceInformationType: \"Direct\"");
                sb.Append("            Normals: *" + (mesh.Normals.Count * 3) + " {\n                a: ");
                for (int i = 0; i < mesh.Normals.Count; i++)
                {
                    var n = mesh.Normals[i];
                    if (i > 0) sb.Append(",");
                    sb.Append(string.Format(CultureInfo.InvariantCulture, "{0:F6},{1:F6},{2:F6}", n.X, n.Y, n.Z));
                }
                sb.AppendLine("\n            }");
                sb.AppendLine("        }");
            }

            // UVs
            if (mesh.UVs.Count > 0)
            {
                sb.AppendLine("        LayerElementUV: 0 {");
                sb.AppendLine("            Version: 101");
                sb.AppendLine("            Name: \"UVChannel_1\"");
                sb.AppendLine("            MappingInformationType: \"ByVertice\"");
                sb.AppendLine("            ReferenceInformationType: \"Direct\"");
                sb.Append("            UV: *" + (mesh.UVs.Count * 2) + " {\n                a: ");
                for (int i = 0; i < mesh.UVs.Count; i++)
                {
                    var uv = mesh.UVs[i];
                    if (i > 0) sb.Append(",");
                    sb.Append(string.Format(CultureInfo.InvariantCulture, "{0:F6},{1:F6}", uv.X, 1f - uv.Y));
                }
                sb.AppendLine("\n            }");
                sb.AppendLine("        }");
            }

            // Layer
            sb.AppendLine("        Layer: 0 {");
            sb.AppendLine("            Version: 100");
            if (mesh.Normals.Count > 0)
            {
                sb.AppendLine("            LayerElement:  {");
                sb.AppendLine("                Type: \"LayerElementNormal\"");
                sb.AppendLine("                TypedIndex: 0");
                sb.AppendLine("            }");
            }
            if (mesh.UVs.Count > 0)
            {
                sb.AppendLine("            LayerElement:  {");
                sb.AppendLine("                Type: \"LayerElementUV\"");
                sb.AppendLine("                TypedIndex: 0");
                sb.AppendLine("            }");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            // Model node
            sb.AppendLine($"    Model: {modelId}, \"Model::{meshName}\", \"Mesh\" {{");
            sb.AppendLine("        Version: 232");
            sb.AppendLine("        Properties70:  {");
            sb.AppendLine("            P: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",0,0,0");
            sb.AppendLine("            P: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",0,0,0");
            sb.AppendLine("            P: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",1,1,1");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            // Material
            sb.AppendLine($"    Material: {materialId}, \"Material::DefaultMaterial\", \"\" {{");
            sb.AppendLine("        Version: 102");
            sb.AppendLine("        Properties70:  {");
            sb.AppendLine("            P: \"DiffuseColor\", \"Color\", \"\", \"A\",0.8,0.8,0.8");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            sb.AppendLine();

            // Connections
            sb.AppendLine("Connections:  {");
            sb.AppendLine($"    C: \"OO\",{modelId},0");
            sb.AppendLine($"    C: \"OO\",{geometryId},{modelId}");
            sb.AppendLine($"    C: \"OO\",{materialId},{modelId}");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
